when:
  - event: push
    branch: main

steps:
  build:
    image: docker/compose:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker-compose build
  
  deploy:
    image: docker/compose:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker-compose up -d