when:
  - event: [push, manual]
    branch: main

steps:
  build:
    image: docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker compose build
  
  deploy:
    image: docker:latest
    commands:
      - docker compose up -d