when:
  - event: [push, manual]
    branch: main

steps:
  build-deploy:
    image: docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker compose up -d --build