when:
  event: push
  branch: main

steps:
  build-image:
    image: docker/compose
    commands:
      - docker-compose build
  
  deploy:
    image: docker/compose
    commands:
      - docker-compose down || true
      - docker-compose up -d