when:
  - event: [push, manual]
    branch: main

steps:
  build:
    image: docker:latest  # â† Utiliser docker:latest au lieu de docker/compose
    commands:
      - docker compose build  # Note: "docker compose" (avec espace) au lieu de "docker-compose"
  
  deploy:
    image: docker:latest
    commands:
      - docker compose up -d