steps:
  build:
    image: docker/compose
    commands:
      - docker-compose build
  
  deploy:
    image: docker/compose
    commands:
      - docker-compose up -d
    when:
      branch: main
      event: push